### ISSUE TITLE
unable to install node-curve25519 globally (npm install -g)

### ISSUE THREAD

**Issue by hackruu** [volschin/node-curve25519#3]
Hello,
i'm trying to install your package globally with command
`npm install curve25519-n -g`

but no matter what i'm doing i'm getting errors like this:
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/curve25519-n/.node-gyp/8.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/curve25519-n/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/curve25519-n/.node-gyp/8.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/curve25519-n/.node-gyp"
```

and at same time, without -g(e.g. in root home directory or in user's home directory) package always installs successfully.

my env:
ubuntu 16.04/nodejs 8.11.1/npm 5.6.0

**Comment by volschin** [comment]
Looks like something is wrong with the environment setting. Where is the .node-gyp directory really located in your global installation?

**Comment by volschin** [comment]
You can circumvent your problem by adding `--unsafe-perm` to your command line.

**Comment by hackruu** [comment]
i see, i tried --unsafe-perms while i should use --unsafe-perm, thanks.
